=== PatrycjaSzczakowska/humanComputer/Zad5/Showroom.xsd
<?xml version="1.0" ?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.przyklad.pl/showroom" xmlns:showroom="http://www.przyklad.pl/showroom">
  <element name="carShowroom">
    <complexType>
      <sequence>
        <element name="brands" type="showroom:brands" minOccurs="1" maxOccurs="1" />
        <element name="cars" type="showroom:cars" minOccurs="1" maxOccurs="1" />
        <element name="metadata" type="showroom:metadata" />
      </sequence>
    </complexType>
    <key name="brandId">
      <selector xpath="./brands/brand" />
      <field xpath="@id" />
    </key>
    <keyref name="brandIdref" refer="showroom:brandId">
      <selector xpath="./cars/car" />
      <field xpath="@brandId" />
    </keyref>
    <key name="carId">
      <selector xpath="./cars/cars" />
      <field xpath="@id" />
    </key>
  </element>

    <simpleType name="boolean">
    <restriction base="normalizedString">
      <pattern value="[YyNn]" />
    </restriction>
  </simpleType>
  <simpleType name="fuelEnum">
    <restriction base="normalizedString">
      <enumeration value="Diesel" />
      <enumeration value="Petrol" />
    </restriction>
  </simpleType>
  <simpleType name="doors">
    <restriction base="integer">
      <pattern value="[2-5]" />
    </restriction>
  </simpleType>
  <simpleType name="seats">
    <restriction base="integer">
      <pattern value="[2-9]" />
    </restriction>
  </simpleType>
  <complexType name="carModel">
    <simpleContent>
      <extension base="normalizedString">
        <attribute name="version" type="normalizedString" use="optional" />
      </extension>
    </simpleContent>
  </complexType>
  <complexType name="carType">
    <simpleContent>
      <extension base="normalizedString">
        <attribute name="doors" type="showroom:doors" use="required" />
        <attribute name="seats" type="showroom:seats" use="required" />
      </extension>
    </simpleContent>
  </complexType>
  <complexType name="carProduction">
    <simpleContent>
      <extension base="short">
        <attribute name="start" type="short" use="required" />
        <attribute name="end" type="short" use="optional" />
        <attribute name="country" type="normalizedString" use="optional" />
      </extension>
    </simpleContent>
  </complexType>
  <complexType name="carEngineCapacity">
    <simpleContent>
      <extension base="short">
        <attribute name="unit" type="normalizedString" fixed="cm3" />
      </extension>
    </simpleContent>
  </complexType>
  <complexType name="carEnginePower">
    <simpleContent>
      <extension base="short">
        <attribute name="unit" type="normalizedString" fixed="KM" />
      </extension>
    </simpleContent>
  </complexType>
  <complexType name="carEngine">
    <sequence>
      <element name="cylindersNumber" type="byte" minOccurs="1" maxOccurs="1" />
      <element name="capacity" type="showroom:carEngineCapacity" minOccurs="1" maxOccurs="1" />
      <element name="power" type="showroom:carEnginePower" minOccurs="1" maxOccurs="1" />
    </sequence>
    <attribute name="fuel" type="showroom:fuelEnum" use="optional" default="Diesel" />
  </complexType>
  <complexType name="carWheeldrive">
    <simpleContent>
      <extension base="normalizedString">
        <attribute name="automatic" type="showroom:boolean" use="required" />
      </extension>
    </simpleContent>
  </complexType>
  <complexType name="carCondition">
    <simpleContent>
      <extension base="normalizedString">
        <attribute name="accidentfree" type="showroom:boolean" use="required" />
        <attribute name="mileage" type="normalizedString" use="required" />
      </extension>
    </simpleContent>
  </complexType>
  <complexType name="carPrice">
    <simpleContent>
      <extension base="int">
        <attribute type="normalizedString" name="currency" use="required" />
      </extension>
    </simpleContent>
  </complexType>
  <complexType name="car">
    <sequence>
      <element name="model" type="showroom:carModel" minOccurs="1" maxOccurs="1" />
      <element name="type" type="showroom:carType" minOccurs="1" maxOccurs="1" />
      <element name="production" type="showroom:carProduction" minOccurs="1" maxOccurs="unbounded" />
      <element name="engine" type="showroom:carEngine" minOccurs="1" maxOccurs="1" />
      <element name="wheeldrive" type="showroom:carWheeldrive" minOccurs="1" maxOccurs="1" />
      <element name="condition" type="showroom:carCondition" minOccurs="1" maxOccurs="1" />
      <element name="lacquer" type="normalizedString" minOccurs="0" maxOccurs="1" />
      <element name="price" type="showroom:carPrice" minOccurs="1" maxOccurs="1" />
    </sequence>
    <attribute type="normalizedString" name="id" use="required" />
    <attribute type="normalizedString" name="brandId" use="required" />
  </complexType>
  <complexType name="cars">
    <sequence>
      <element name="car" type="showroom:car" minOccurs="1" maxOccurs="unbounded" />
    </sequence>
  </complexType>


  <simpleType name="type">
    <restriction base="integer">
      <pattern value="[2][0-9][0-9][0-9][0-9][0-9]" />
    </restriction>
  </simpleType>
  <simpleType name="comment">
    <restriction base="string">
      <maxLength value="1000" />
    </restriction>
  </simpleType>
  <complexType name="student">
    <simpleContent>
      <extension base="normalizedString">
        <attribute name="index" type="showroom:type" use="required" />
      </extension>
    </simpleContent>
  </complexType>
  <complexType name="metadata">
    <choice minOccurs="0" maxOccurs="unbounded">
      <element name="comment" type="showroom:comment" />
      <element name="author" type="showroom:student" minOccurs="2" maxOccurs="2" />
      <element name="modificationDate" type="date" minOccurs="1" maxOccurs="1" />
    </choice>
  </complexType>


   <simpleType name="continentEnum">
    <restriction base="string">
      <enumeration value="Europe" />
      <enumeration value="Asia" />
      <enumeration value="North_America" />
      <enumeration value="South_America" />
      <enumeration value="Africa" />
      <enumeration value="Austalia_and_Oceania" />
    </restriction>
  </simpleType>
  <complexType name="brandCountry">
    <simpleContent>
      <extension base="normalizedString">
        <attribute name="continent" type="showroom:continentEnum" use="optional" default="Europe" />
      </extension>
    </simpleContent>
  </complexType>
  <complexType name="brand">
    <sequence>
      <element name="name" type="normalizedString" minOccurs="1" maxOccurs="1" />
      <element name="country" type="showroom:brandCountry" minOccurs="1" maxOccurs="1" />
      <element name="headquarters" type="normalizedString" minOccurs="0" maxOccurs="unbounded" />
      <element name="chairman" type="normalizedString" minOccurs="0" maxOccurs="1" />
    </sequence>
    <attribute name="id" type="normalizedString" use="required" />
  </complexType>
  <complexType name="brands">
    <sequence>
      <element name="brand" type="showroom:brand" minOccurs="1" maxOccurs="unbounded" />
    </sequence>
  </complexType>
</schema>

=== PatrycjaSzczakowska/humanComputer/Zadanie5/Auta2.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?><ns2:carShowroom xmlns:ns2="http://www.przyklad.pl/showroom" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Showroom.xsd"><brands><brand id="jaguar"><name>Jaguar</name><country continent="Europe">UK</country><headquarters>Coventry, UK</headquarters><chairman>Ralf Speth</chairman></brand><brand id="renault"><name>Renault</name><country continent="Europe">France</country><headquarters>Boulogne-Billancourt, France</headquarters><chairman>Thierry Bolloré</chairman></brand><brand id="jeep"><name>Jeep</name><country continent="North_America">U.S.</country><headquarters>Toledo, Ohio, U.S.</headquarters><chairman>Michael Manley</chairman></brand><brand id="landRover"><name>Land Rover</name><country continent="Europe">UK</country><headquarters>Coventry, UK</headquarters><chairman>Ralf Speth</chairman></brand></brands><cars><car id="c21" brandId="renault"><model version="IV">Megane</model><type doors="5" seats="5">compact</type><production start="2016">2016</production><engine fuel="Petrol"><cylindersNumber>4</cylindersNumber><capacity>1200</capacity><power>101</power></engine><wheeldrive automatic="n">front-wheel</wheeldrive><condition accidentfree="y" mileage="346000 km">used</condition><lacquer>white</lacquer><price currency="PLN">27999</price></car><car id="c22" brandId="landRover"><model version="setVersion">setModel</model><type doors="5" seats="5">setType</type><production start="2019">2019</production><engine><cylindersNumber>10</cylindersNumber><capacity>100</capacity><power>10</power></engine><wheeldrive automatic="n">setCarWheeldrive</wheeldrive><condition accidentfree="y" mileage="cerConditionMileage">setCondition</condition><lacquer>setCarLacquer</lacquer><price currency="$">1000</price></car></cars><metadata><comment>Programowanie komunikacji komputer-człowiek. Zadanie 1.</comment><author index="210198">Jędrzej Hasiura</author><author index="210332">Patrycja Szczakowska</author><modificationDate>2019-03-19</modificationDate></metadata></ns2:carShowroom>
